openapi: 3.1.0
x-internal: true
info:
  version: 1.0.0
  title: Internal API
  termsOfService: 'https://example.com/terms/'
  contact:
    email: support@dynamicore.io
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://dynamicore.io/static/media/logotipo.db0f4360d19b7d85897ec7b8e73814f2.svg'
  description:
    $ref: ./info-description.md
tags:
  - name: Authentication
    description: 
      $ref: ./files_descriptions/authorization/info-auth.md
  - name: Types
    description: ''
  - name: Catalogs
    description: ''
  - name: Clients
    description: ''
  - name: Accounts
    description: ''
  - name: MARKETPLACE
    description: ''
  - name: SAT
    description: ''
  - name: Mifiel
    description: ''
  - name: Conekta
    description: ''
  - name: Errors
    description: 
      $ref: ./files_descriptions/errors/info-erros.md
  - name: Campaigns
    description: ''
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  /types-clients: 
    $ref: paths/types-clients.yaml
  /types:
    $ref: 'paths/types-products.yaml'
  /catalogs: 
    $ref: 'paths/catalogs-clients.yaml'
  /https://api.dynamicore.io/private/clients:
    $ref: paths/catalogs-products.yaml
  /create-clients:
    $ref: paths/create-client.yaml
  /update-clients:
    $ref: paths/update-client.yaml
  /list-clients:
    $ref: paths/list-clients.yaml
  /upload-documents:
    $ref: paths/upload-documents.yaml
  /get-sat:
    $ref: paths/get-sat.yaml
  /get-credit-store:
    $ref: paths/get-credit-store.yaml
  /create-accounts:
    $ref: paths/accounts/create-accounts.yaml
  /customer-account:
    $ref: paths/accounts/customer-account.yaml
  /account-transactions:
    $ref: paths/accounts/account-transaction.yaml
  /account-payments:
    $ref: paths/accounts/account-payments.yaml
  /load-keys:
    $ref: paths/marketplace/load-keys.yaml
  /sync-data:
    $ref: paths/marketplace/sync-data.yaml
  /get-data:
    $ref: paths/marketplace/get-data.yaml
  /create-document:
    $ref: paths/mifiel/create-document.yaml
  /widget:
    $ref: paths/mifiel/widget.yaml
  /get-document:
    $ref: paths/mifiel/get-document.yaml
  /create_order:
    $ref: paths/conekta/create_order.yaml
  /get_order:
    $ref: paths/conekta/get_order.yaml
  /get_reference_pending:
    $ref: paths/conekta/get_reference.yaml
  /get_campaign:
    $ref: paths/campaigns/get-campaigns.yaml
  /eval_campaign:
    $ref: paths/campaigns/eval-campaign.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      x-internal: true
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
security:
  - main_auth: []
  - api_key: []
