openapi: 3.1.0
info:
  version: 1.0.0
  title: Dynamicore API
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://docs.dynamicore.io/images/logo-bcfbcf05.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Authentication
    description: 
      $ref: ./files_descriptions/authorization/info-auth.md
  - name: Types
    description: ''
  - name: Catalogs
    description: ''
  - name: Clients
    description: ''
  - name: Accounts
    description: ''
  - name: MARKETPLACE
    description: ''
  - name: SAT
    description: ''
  - name: Mifiel
    description: ''
  - name: Echo
    description: Example echo operations.
  - name: User
    description: Operations about users.
  - name: Tag MUNDO
    description: This is a tag description.
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  /types-clients: 
    $ref: paths/types-clients.yaml
  /types:
    $ref: 'paths/types-products.yaml'
  /catalogs: 
    $ref: 'paths/catalogs-clients.yaml'
  /https://api.dynamicore.io/private/clients:
    $ref: paths/catalogs-products.yaml
  /create-clients:
    $ref: paths/create-client.yaml
  /update-clients:
    $ref: paths/update-client.yaml
  /list-clients:
    $ref: paths/list-clients.yaml
  /upload-documents:
    $ref: paths/upload-documents.yaml
  /get-sat:
    $ref: paths/get-sat.yaml
  /get-credit-store:
    $ref: paths/get-credit-store.yaml
  /create-accounts:
    $ref: paths/accounts/create-accounts.yaml
  /customer-account:
    $ref: paths/accounts/customer-account.yaml
  /account-transactions:
    $ref: paths/accounts/account-transaction.yaml
  /account-payments:
    $ref: paths/accounts/account-payments.yaml
  /load-keys:
    $ref: paths/marketplace/load-keys.yaml
  /sync-data:
    $ref: paths/marketplace/sync-data.yaml
  /get-data:
    $ref: paths/marketplace/get-data.yaml
  /create-document:
    $ref: paths/mifiel/create-document.yaml
  /widget:
    $ref: paths/mifiel/widget.yaml
  /get-document:
    $ref: paths/mifiel/get-document.yaml
  /echo:
    $ref: paths/echo.yaml
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
