get:
  tags:
    - Products
  summary: Get Products types
  description: 
    $ref: ../../files_descriptions/products/info-get-products-types.md
  x-internal: true
  operationId: get_products_types
  responses:
    '200':
      description: OK
      headers:
        X-Rate-Limit:
          description: calls per hour allowed by the user
          schema:
            type: integer
            format: int32
        X-Expires-After:
          $ref: ../../components/headers/ExpiresAfter.yaml
          content:
          application/json:
            schema:
              type: object
              example: {
                "status": "success",
                "message": {
                    "code": 1,
                    "total": 2,
                    "data": [
                        {
                            "id": 92,
                            "name": "Credito",
                            "company": 3027,
                            "description": "Ejemplo template #3",
                            "alias": "Credito",
                            "template": [
                                {
                                    "name": "start_date",
                                    "type": "datetime",
                                    "field": 67,
                                    "score": 1,
                                    "validate": {},
                                    "displayname": "Día",
                                    "displaytype": "string"
                                }
                            ]
                        },
                        {
                            "id": 93,
                            "name": "Credito",
                            "company": 3027,
                            "description": "Ejemplo template #3",
                            "alias": "MasterCel",
                            "template": [
                                {
                                    "name": "start_date",
                                    "type": "datetime",
                                    "field": 67,
                                    "score": 1,
                                    "validate": {},
                                    "displayname": "Día mensual de pago",
                                    "displaytype": "string"
                                }
                            ]
                        }
                    ]
                }
            }
          required: true
        application/xml:
          schema:
            type: string
        text/csv:
          schema:
            type: string
    '400': 
      description: Unauthorized
  requestBody:
    content:
      application/json:
        schema:
          x-internal: true
          type: object
          example: {
            "status": "success",
            "message": {
              "code": 1,
              "total": 2,
              "data": [
                  {
                      "id": 92,
                      "name": "Credito",
                      "company": 3027,
                      "description": "Ejemplo template #3",
                      "alias": "Credito",
                      "template": [
                          {
                              "name": "start_date",
                              "type": "datetime",
                              "field": 67,
                              "score": 1,
                              "validate": {},
                              "displayname": "Día",
                              "displaytype": "string"
                          }
                      ]
                  },
                  {
                      "id": 93,
                      "name": "Credito",
                      "company": 3027,
                      "description": "Ejemplo template #3",
                      "alias": "Alias Example",
                      "template": [
                          {
                              "name": "start_date",
                              "type": "datetime",
                              "field": 67,
                              "score": 1,
                              "validate": {},
                              "displayname": "Día mensual de pago",
                              "displaytype": "string"
                          }
                      ]
                  }
              ]
            }
        }
    required: true
  